<?php
$pageTitle = "Home";
include "view-header.php";
?>
<div class="container">

    <h1>HoMe</h1>
    <p>The Database and database content for this project was generated by ChatGPT</p>
</div>
<?php
include "view-footer.php";
?>